# Generated by Django 5.1.7 on 2025-03-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Classification level (0-100, where 0 is DEV)'),
        ),
        migrations.AddField(
            model_name='waapuser',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Classification level (0-100, where 0 is DEV)', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='waap.classification'),
        ),
        migrations.AlterField(
            model_name='waapuser',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='waap.classification'),
        ),
    ]
