# Generated by Django 5.1.7 on 2025-03-08 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waap", "0002_onetimetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_postings",
                to="waap.waapuser",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="deletion_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
