# Generated by Django 5.1.7 on 2025-03-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waap", "0003_jobposting_creator_jobposting_deletion_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_email", models.EmailField(max_length=254)),
                ("sender_email_hash", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="waap.jobposting",
                    ),
                ),
            ],
        ),
    ]
