# Generated by Django 5.1.7 on 2025-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waap", "0004_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="moderation_by",
            field=models.CharField(
                blank=True,
                help_text="Username of the admin who performed the last moderation action",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last moderation action was taken",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_notes",
            field=models.TextField(
                blank=True,
                help_text="Admin notes about moderation decisions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("FLAGGED", "Flagged for Review"),
                    ("INAPPROPRIATE", "Marked as Inappropriate"),
                    ("REMOVED", "Removed"),
                ],
                default="APPROVED",
                help_text="Current moderation status of the job posting",
                max_length=20,
            ),
        ),
    ]
