# Generated by Django 5.1.7 on 2025-03-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual'), ('EC-06', 'EC-06'), ('IT-02', 'IT-02'), ('PM-04', 'PM-04')], max_length=20)),
                ('alternation_criteria', models.JSONField(blank=True, default=dict)),
                ('language_profile', models.CharField(choices=[('ENGLISH', 'English Essential'), ('FRENCH', 'French Essential'), ('BILINGUAL', 'Bilingual (BBB/BBB)'), ('ENGLISH_PREFERRED', 'English Preferred'), ('FRENCH_PREFERRED', 'French Preferred')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('moderation_status', models.CharField(choices=[('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Review'), ('INAPPROPRIATE', 'Marked as Inappropriate'), ('REMOVED', 'Removed')], default='APPROVED', help_text='Current moderation status of the job posting', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, help_text='Admin notes about moderation decisions', null=True)),
                ('moderation_date', models.DateTimeField(blank=True, help_text='When the last moderation action was taken', null=True)),
                ('moderation_by', models.CharField(blank=True, help_text='Username of the admin who performed the last moderation action', max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='waap.department')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_email_hash', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='waap.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='WaapUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual'), ('EC-06', 'EC-06'), ('IT-02', 'IT-02'), ('PM-04', 'PM-04')], max_length=20, null=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='waap.department')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='waap.waapuser'),
        ),
    ]
