# Generated by Django 5.1.7 on 2025-03-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waap', '0002_classification_jobposting_level_waapuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='alternation_type',
            field=models.CharField(choices=[('SEEKING', 'Seeking - Affected Employee'), ('OFFERING', 'Offering - Unaffected Employee')], default='SEEKING', max_length=20),
        ),
    ]
